# Generated by Django 6.0 on 2026-01-01 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="The Star", max_length=255)),
                ("author", models.CharField(default="H.G. Wells", max_length=255)),
                ("slug", models.SlugField(default="the-star", unique=True)),
                (
                    "manuscript_path",
                    models.CharField(
                        default="manuscripts/the_star.txt", max_length=512
                    ),
                ),
                (
                    "annotations_path",
                    models.CharField(
                        default="annotations/the_star_notes.json", max_length=512
                    ),
                ),
                ("cover_path", models.CharField(blank=True, max_length=512, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EPUBBuild",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("building", "Building"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "output_path",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                ("chapter_count", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="builds",
                        to="books.book",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
