# Generated by Django 6.0 on 2026-02-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="epubbuild",
            name="annotation_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="epubbuild",
            name="current_stage",
            field=models.CharField(default="pending", max_length=50),
        ),
        migrations.AddField(
            model_name="epubbuild",
            name="section_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="epubbuild",
            name="stage_log",
            field=models.TextField(default="[]"),
        ),
        migrations.AlterField(
            model_name="book",
            name="annotations_path",
            field=models.CharField(default="", max_length=512),
        ),
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.CharField(default="Unknown Author", max_length=255),
        ),
        migrations.AlterField(
            model_name="book",
            name="manuscript_path",
            field=models.CharField(default="", max_length=512),
        ),
        migrations.AlterField(
            model_name="book",
            name="slug",
            field=models.SlugField(default="untitled", unique=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(default="Untitled", max_length=255),
        ),
        migrations.AlterField(
            model_name="epubbuild",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("ingesting", "Ingesting Text"),
                    ("annotating", "Generating Annotations"),
                    ("analyzing", "Comprehensive Analysis"),
                    ("building", "Building EPUB"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
