# Generated by Django 6.0 on 2026-02-02 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_epubbuild_annotation_count_epubbuild_current_stage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Friendly name for this configuration", max_length=100
                    ),
                ),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("ollama", "Ollama (Local/Network)"),
                            ("openai", "OpenAI API"),
                        ],
                        default="ollama",
                        max_length=20,
                    ),
                ),
                (
                    "api_url",
                    models.URLField(
                        default="http://localhost:11434",
                        help_text="For Ollama: http://localhost:11434 or http://your-server:11434. For OpenAI: https://api.openai.com/v1",
                        max_length=255,
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True,
                        help_text="Required for OpenAI, optional for Ollama",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "default_model",
                    models.CharField(
                        default="llama3.2:1b",
                        help_text="Model to use (e.g., llama3.2:1b, gpt-4o-mini)",
                        max_length=100,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Enable/disable this provider"
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Use as the primary AI provider"
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="Higher priority = tried first (for fallback)",
                    ),
                ),
                ("last_tested", models.DateTimeField(blank=True, null=True)),
                ("last_test_success", models.BooleanField(blank=True, null=True)),
                ("last_test_message", models.TextField(blank=True, default="")),
                (
                    "available_models",
                    models.TextField(
                        blank=True,
                        default="[]",
                        help_text="JSON list of available models",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AI Provider",
                "verbose_name_plural": "AI Providers",
                "ordering": ["-is_primary", "-priority", "name"],
            },
        ),
    ]
