# Generated by Django 6.0 on 2026-02-03 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_add_ai_provider"),
    ]

    operations = [
        migrations.CreateModel(
            name="TTSProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Friendly name", max_length=100)),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("riva", "NVIDIA Riva"),
                            ("pyttsx3", "pyttsx3 (Local)"),
                            ("gtts", "Google TTS"),
                            ("azure", "Azure Speech"),
                        ],
                        default="riva",
                        max_length=20,
                    ),
                ),
                (
                    "server_url",
                    models.CharField(
                        default="localhost:50051",
                        help_text="Server address (e.g., localhost:50051 for Riva)",
                        max_length=255,
                    ),
                ),
                ("api_key", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "sample_rate",
                    models.IntegerField(
                        default=44100, help_text="Audio sample rate in Hz"
                    ),
                ),
                (
                    "output_format",
                    models.CharField(
                        default="wav",
                        help_text="Output format (wav, mp3)",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_primary", models.BooleanField(default=False)),
                ("last_tested", models.DateTimeField(blank=True, null=True)),
                ("last_test_success", models.BooleanField(blank=True, null=True)),
                ("last_test_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "TTS Provider",
                "verbose_name_plural": "TTS Providers",
                "ordering": ["-is_primary", "name"],
            },
        ),
        migrations.CreateModel(
            name="VoiceProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Voice name", max_length=100)),
                (
                    "voice_id",
                    models.CharField(
                        help_text="Voice ID from TTS provider", max_length=200
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("narrator", "Narrator"),
                            ("bob_annotation", "Bob (Annotations)"),
                            ("character", "Character"),
                        ],
                        default="character",
                        max_length=20,
                    ),
                ),
                (
                    "pitch",
                    models.FloatField(
                        default=1.0, help_text="Pitch multiplier (0.5-2.0)"
                    ),
                ),
                (
                    "speed",
                    models.FloatField(
                        default=1.0, help_text="Speed multiplier (0.5-2.0)"
                    ),
                ),
                (
                    "tone",
                    models.CharField(
                        default="neutral",
                        help_text="Tone (neutral, dramatic, gentle, stern)",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Voice description"),
                ),
                (
                    "sample_audio_path",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                (
                    "sample_text",
                    models.TextField(
                        blank=True,
                        default="Hello, I am a voice for NullRecords Press. This is a preview of how I sound.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Voice Profile",
                "verbose_name_plural": "Voice Profiles",
                "ordering": ["role", "name"],
            },
        ),
        migrations.CreateModel(
            name="AudioBuild",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("generating", "Generating Audio"),
                            ("combining", "Combining Tracks"),
                            ("encoding", "Encoding MP3"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "include_annotations",
                    models.BooleanField(
                        default=True, help_text="Include Bob's annotations"
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("current_section", models.IntegerField(default=0)),
                ("total_sections", models.IntegerField(default=0)),
                (
                    "output_path",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                ("duration_seconds", models.IntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audio_builds",
                        to="books.book",
                    ),
                ),
                (
                    "tts_provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="books.ttsprovider",
                    ),
                ),
                (
                    "bob_voice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bob_builds",
                        to="books.voiceprofile",
                    ),
                ),
                (
                    "narrator_voice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="narrator_builds",
                        to="books.voiceprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audio Build",
                "verbose_name_plural": "Audio Builds",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CharacterVoiceMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "character_name",
                    models.CharField(
                        help_text="Character name (e.g., 'Gregor', 'Grete')",
                        max_length=100,
                    ),
                ),
                (
                    "speech_patterns",
                    models.TextField(
                        blank=True,
                        help_text="JSON list of regex patterns to detect this character's speech",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_voices",
                        to="books.book",
                    ),
                ),
                (
                    "voice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_mappings",
                        to="books.voiceprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Character Voice Mapping",
                "verbose_name_plural": "Character Voice Mappings",
                "ordering": ["book", "character_name"],
                "unique_together": {("book", "character_name")},
            },
        ),
    ]
