# Generated by Django 6.0 on 2026-02-03 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_ttsprovider_voiceprofile_audiobuild_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ttsprovider",
            name="cpu_offload",
            field=models.BooleanField(
                default=False,
                help_text="Use CPU offload for PersonaPlex (if GPU VRAM is insufficient)",
            ),
        ),
        migrations.AddField(
            model_name="voiceprofile",
            name="persona_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="PersonaPlex persona description (e.g., 'You are a dramatic narrator with a deep voice')",
            ),
        ),
        migrations.AddField(
            model_name="voiceprofile",
            name="voice_prompt_path",
            field=models.CharField(
                blank=True,
                help_text="Path to 5-10 second audio file for PersonaPlex voice cloning",
                max_length=512,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ttsprovider",
            name="api_key",
            field=models.CharField(
                blank=True,
                help_text="HuggingFace token for PersonaPlex, or API key for other providers",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ttsprovider",
            name="provider_type",
            field=models.CharField(
                choices=[
                    ("personaplex", "NVIDIA PersonaPlex-7B (HuggingFace)"),
                    ("riva", "NVIDIA Riva"),
                    ("pyttsx3", "pyttsx3 (Local, No GPU)"),
                    ("gtts", "Google TTS (Online)"),
                    ("azure", "Azure Speech"),
                ],
                default="personaplex",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ttsprovider",
            name="sample_rate",
            field=models.IntegerField(
                default=24000,
                help_text="Audio sample rate in Hz (24000 for PersonaPlex)",
            ),
        ),
        migrations.AlterField(
            model_name="ttsprovider",
            name="server_url",
            field=models.CharField(
                default="wss://localhost:8443",
                help_text="Server address (wss://localhost:8443 for PersonaPlex, localhost:50051 for Riva)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="voiceprofile",
            name="voice_id",
            field=models.CharField(
                blank=True,
                help_text="Voice ID from TTS provider (for Riva/standard TTS)",
                max_length=200,
            ),
        ),
    ]
