# Generated by Django 6.0 on 2026-04-10 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_ttsprovider_cpu_offload_voiceprofile_persona_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="annotation_approach",
            field=models.TextField(
                blank=True,
                default="",
                help_text="AI-generated annotation approach/plan for this book",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="annotation_conversation",
            field=models.TextField(
                blank=True,
                default="[]",
                help_text="JSON array of conversation history about annotation planning",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="annotation_instructions",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Custom instructions for Bob the Humanist when annotating this book",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="planning_completed",
            field=models.BooleanField(
                default=False,
                help_text="Whether annotation planning has been completed",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="preferred_model",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Preferred AI model for annotating this book (e.g., qwen2.5:7b)",
                max_length=100,
            ),
        ),
    ]
