# Generated by Django 6.0 on 2026-04-10 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0006_book_annotation_approach_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ttsprovider",
            name="provider_type",
            field=models.CharField(
                choices=[
                    ("personaplex", "NVIDIA PersonaPlex-7B (HuggingFace)"),
                    ("riva", "NVIDIA Riva"),
                    ("edge-tts", "Microsoft Edge TTS (Neural, Online)"),
                    ("pyttsx3", "pyttsx3/macOS (Local)"),
                    ("gtts", "Google TTS (Online)"),
                    ("azure", "Azure Speech"),
                ],
                default="personaplex",
                max_length=20,
            ),
        ),
    ]
