# Generated by Django 6.0 on 2026-04-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0007_alter_ttsprovider_provider_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="AudioAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Asset name", max_length=100)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("bumper", "Intro Bumper"),
                            ("outro", "Outro"),
                            ("legal", "Legal Disclaimer"),
                            ("transition", "Transition Sound"),
                            ("effect", "Sound Effect"),
                        ],
                        default="bumper",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "audio_file",
                    models.FileField(
                        blank=True,
                        help_text="Upload WAV or MP3 file",
                        null=True,
                        upload_to="audio_assets/",
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True,
                        help_text="Alternative: path to existing audio file",
                        max_length=512,
                        null=True,
                    ),
                ),
                (
                    "source_text",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Original text (if generated from TTS)",
                    ),
                ),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                ("sample_rate", models.IntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Audio Asset",
                "verbose_name_plural": "Audio Assets",
                "ordering": ["asset_type", "name"],
            },
        ),
        migrations.AddField(
            model_name="audiobuild",
            name="bumper_audio_path",
            field=models.CharField(
                blank=True,
                help_text="Path to intro bumper audio file",
                max_length=512,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="audiobuild",
            name="end_section",
            field=models.IntegerField(
                blank=True,
                help_text="Section number to end narration at (leave blank for all)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="audiobuild",
            name="include_legal_disclaimer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="audiobuild",
            name="legal_disclaimer_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Legal disclaimer text to be read at the beginning",
            ),
        ),
        migrations.AddField(
            model_name="audiobuild",
            name="outro_audio_path",
            field=models.CharField(
                blank=True,
                help_text="Path to outro audio file",
                max_length=512,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="audiobuild",
            name="start_section",
            field=models.IntegerField(
                default=1, help_text="Section number to start narration from (1-based)"
            ),
        ),
        migrations.AddField(
            model_name="audiobuild",
            name="style_prompt",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Style instructions for voice (e.g., 'Read in a humorous, laid-back tone with a southern accent')",
            ),
        ),
    ]
