# Generated by Django 5.2.13 on 2026-04-11 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0008_add_audiobook_enhancements"),
    ]

    operations = [
        migrations.AddField(
            model_name="voiceprofile",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                help_text="TTS provider this voice is configured for",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="voices",
                to="books.ttsprovider",
            ),
        ),
        migrations.AlterField(
            model_name="aiprovider",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="audioasset",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="audiobuild",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="charactervoicemapping",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="epubbuild",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="ttsprovider",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="ttsprovider",
            name="provider_type",
            field=models.CharField(
                choices=[
                    ("personaplex", "NVIDIA PersonaPlex-7B (HuggingFace)"),
                    ("riva", "NVIDIA Riva"),
                    ("edge-tts", "Microsoft Edge TTS (Neural, Online)"),
                    ("xtts", "Coqui XTTS v2 (Local, Expressive)"),
                    ("pyttsx3", "pyttsx3/macOS (Local)"),
                    ("piper", "Piper TTS (Offline, Fast)"),
                    ("gtts", "Google TTS (Online)"),
                    ("azure", "Azure Speech"),
                ],
                default="personaplex",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="voiceprofile",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="voiceprofile",
            name="voice_id",
            field=models.CharField(
                blank=True,
                help_text="Voice ID from TTS provider (e.g., en-US-AvaNeural for Edge TTS)",
                max_length=200,
            ),
        ),
    ]
