# Generated by Django 5.2.13 on 2026-04-20 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0009_voiceprofile_provider_alter_aiprovider_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="audiobuild",
            name="bob_voice",
        ),
        migrations.AddField(
            model_name="audiobuild",
            name="annotator_voice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="annotator_builds",
                to="books.voiceprofile",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="annotation_theme",
            field=models.CharField(
                choices=[
                    ("bobs_somewhat_humanist", "Bob's Somewhat Humanist"),
                    ("scientific_review", "Scientific Review"),
                    ("cyberpunk_neon", "Cyberpunk Neon"),
                    ("textbook_classic", "Textbook Classic"),
                ],
                default="bobs_somewhat_humanist",
                help_text="Visual theme and annotator persona for this book's annotations",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="custom_annotator_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Override the theme's default annotator name",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="custom_background_color",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Override background color (hex, e.g. #F5F5DC)",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="custom_icon_letter",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Override the annotator icon letter (1-2 chars)",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="custom_primary_color",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Override primary color (hex, e.g. #B87333)",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="audiobuild",
            name="include_annotations",
            field=models.BooleanField(
                default=True, help_text="Include annotations in audio"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="annotation_instructions",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Custom instructions for the annotator when annotating this book",
            ),
        ),
        migrations.AlterField(
            model_name="voiceprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("narrator", "Narrator"),
                    ("annotator", "Annotator"),
                    ("character", "Character"),
                ],
                default="character",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="voiceprofile",
            name="sample_text",
            field=models.TextField(
                blank=True,
                default="Hello, I am a voice for the publisher. This is a preview of how I sound.",
            ),
        ),
    ]
