# Generated by Django 5.2.13 on 2026-04-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0010_add_annotation_themes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audioasset",
            name="asset_type",
            field=models.CharField(
                choices=[
                    ("bumper", "Intro Bumper"),
                    ("outro", "Outro"),
                    ("legal", "Legal Disclaimer"),
                    ("transition", "Transition Sound"),
                    ("effect", "Sound Effect"),
                    ("stinger", "Annotation Stinger"),
                ],
                default="bumper",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ttsprovider",
            name="provider_type",
            field=models.CharField(
                choices=[
                    ("personaplex", "NVIDIA PersonaPlex-7B (HuggingFace)"),
                    ("riva", "NVIDIA Riva"),
                    ("edge-tts", "Microsoft Edge TTS (Neural, Online)"),
                    ("xtts", "Coqui XTTS v2 (Local, Expressive)"),
                    ("pyttsx3", "pyttsx3/macOS (Local)"),
                    ("piper", "Piper TTS (Offline, Fast)"),
                    ("gtts", "Google TTS (Online)"),
                    ("azure", "Azure Speech"),
                ],
                default="edge-tts",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ttsprovider",
            name="sample_rate",
            field=models.IntegerField(
                default=24000, help_text="Audio sample rate in Hz"
            ),
        ),
        migrations.AlterField(
            model_name="ttsprovider",
            name="server_url",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Server address (e.g., localhost:50051 for Riva, wss://localhost:8443 for PersonaPlex)",
                max_length=255,
            ),
        ),
    ]
